// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cumsd
NumericVector cumsd(NumericVector x);
RcppExport SEXP ResearchGroupTools_cumsd(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cumsd(x));
    return rcpp_result_gen;
END_RCPP
}
// cumskewness
NumericVector cumskewness(NumericVector x);
RcppExport SEXP ResearchGroupTools_cumskewness(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cumskewness(x));
    return rcpp_result_gen;
END_RCPP
}
// cumkurtosis
NumericVector cumkurtosis(NumericVector x);
RcppExport SEXP ResearchGroupTools_cumkurtosis(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cumkurtosis(x));
    return rcpp_result_gen;
END_RCPP
}
// cumadev
NumericVector cumadev(NumericVector x);
RcppExport SEXP ResearchGroupTools_cumadev(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cumadev(x));
    return rcpp_result_gen;
END_RCPP
}
