# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cumsd <- function(x) {
    .Call('ResearchGroupTools_cumsd', PACKAGE = 'ResearchGroupTools', x)
}

#' @export
cumskewness <- function(x) {
    .Call('ResearchGroupTools_cumskewness', PACKAGE = 'ResearchGroupTools', x)
}

#' @export
cumkurtosis <- function(x) {
    .Call('ResearchGroupTools_cumkurtosis', PACKAGE = 'ResearchGroupTools', x)
}

#' @export
cumadev <- function(x) {
    .Call('ResearchGroupTools_cumadev', PACKAGE = 'ResearchGroupTools', x)
}

