# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cumulativate versions of skewness, kurtosis, sd, adv
#'
#' ResearchGroupTools adds \code{cumskewness}, \code{cumkurtosis},
#' \code{cumadev}, and \code{cumsd} to complete
#' R's set of cumulate functions to match the aggregation functions available
#' in most databases
#'
#' @param x For \code{cumskewness}, \code{cumkurtosis}, \code{cumsd},
#' \code{cumadv} an integer or numeric vector
#' @export
cumsd <- function(x) {
    .Call('ResearchGroupTools_cumsd', PACKAGE = 'ResearchGroupTools', x)
}

#' @export
#' @rdname cumsd
cumskewness <- function(x) {
    .Call('ResearchGroupTools_cumskewness', PACKAGE = 'ResearchGroupTools', x)
}

#' @export
#' @rdname cumsd
cumkurtosis <- function(x) {
    .Call('ResearchGroupTools_cumkurtosis', PACKAGE = 'ResearchGroupTools', x)
}

#' @export
#' @rdname cumsd
cumadev <- function(x) {
    .Call('ResearchGroupTools_cumadev', PACKAGE = 'ResearchGroupTools', x)
}

